spring:
  datasource:
    url: jdbc:mysql://10.15.42.36:3306/selenium?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: true
jasypt:
  encryptor:
    password: joshua
server:
  port: 8080

test:
  config: test-config